version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana.tv2.dk
      ELASTICSEARCH_URL: http://elasticsearch1:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    ports:
      - 5601:5601

networks:
  default:
    external:
      name: elastic_esnet
